services:
  numeric-generate-service:
    image: numeric-generate-service:latest
    build: .
    restart: "no"
    ports:
      - "8080:8080"
  redis:
    image: redis:7.4.2
    restart: "no"
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    volumes:
      - ./redis/redis-prod.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5