spring:
  application:
    name: numeric-generate-service
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: password

redis:
  key: orders_code_5

springdoc:
  api-docs:
    path: /v1/api-docs
    enabled: true
  swagger-ui:
    enabled: true